export const DefaultVideoAttributesMap = {
  AUTOPLAY: 'autoplay',
  CROSSORIGIN: 'crossorigin',
  LOOP: 'loop',
  MUTED: 'muted',
  PLAYSINLINE: 'playsinline',
  SRC: 'src',
  POSTER: 'poster',
  PRELOAD: 'preload',
};

export const DefaultVideoEventsMap = {
  ABORT: 'abort',
  CANPLAY: 'canplay',
  CANPLAYTHROUGH: 'canplaythrough',
  DURATIONCHANGE: 'durationchange',
  EMPTIED: 'emptied',
  ENDED: 'ended',
  ERROR: 'error',
  LOADEDDATA: 'loadeddata',
  LOADEDMETADATA: 'loadedmetadata',
  LOADSTART: 'loadstart',
  PAUSE: 'pause',
  PLAY: 'play',
  PLAYING: 'playing',
  PROGRESS: 'progress',
  RATECHANGE: 'ratechange',
  SEEKED: 'seeked',
  SEEKING: 'seeking',
  STALLED: 'stalled',
  SUSPEND: 'suspend',
  TIMEUPDATE: 'timeupdate',
  VOLUMECHANGE: 'volumechange',
  WAITING: 'waiting',
} as {[key: string]: string};
